# Generated by Django 6.0.3 on 2026-04-21 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_post_creator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='status',
            new_name='active',
        ),
    ]
